apiVersion: apps/v1
kind: Deployment
metadata:
  name: OrderDelivery
  labels:
    app: OrderDelivery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: OrderDelivery
  template:
    metadata:
      labels:
        app: OrderDelivery
    spec:
      containers:
        - name: OrderDelivery
          image: "username/OrderDelivery:latest"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 15
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 15
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
